name: build and deploy laravel

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
      build:
        runs-on: ubuntu-latest
        name: Build and Push
        steps:
          - name: Checkout
            uses: actions/checkout@v2
          - name: Deployment
    
            uses: appleboy/ssh-action@main
            env:
              REPO: self
              BRANCH: master  
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
              MESSAGE: "Build: ({sha}) {msg}"
      
              script: |
      
                cd /home/prophecius/public_html/curevive.prophecius.com
      
                git checkout -f 
      
                git pull
          
            